### ISSUE TITLE
Running the Service Self Hosted

### ISSUE THREAD

**Issue by satyajitghana** [bimdata/platform-back#36]
Is it possible to run the entire service self-hosted ?

I see that there is a `platform-back` and `platform` repositories, but they reply on API's hosted on  `bimdata.io` and those api's source code and setup has not been released.

I would like to host all of those services on my end.

**Comment by Amoki** [comment]
The API is not public. But we provide an on-premise solution. You can find more information here: https://bimdata.io/en/bimdata-on-premise-solution/
